### ISSUE TITLE
lagging while scrolling page

### ISSUE THREAD

**Issue by oolyvi** [developerchunk/Custom-Pie-Chart-Jetpack-Compose#2]
If you want your screen without any lags or misbehaviour, you can add this `.offset { IntOffset.Zero }` little part to your code to solve that issue:

```
// Pie Chart using Canvas Arc
        Box(
            modifier = Modifier
                .offset { IntOffset.Zero }   // I mean here
                .size(animateSize.dp),
            contentAlignment = Alignment.Center
        ) {
            Canvas(
                modifier = Modifier
                    .size(radiusOuter * 2f)
                    .rotate(animateRotation)
            ) {
                floatValue.forEachIndexed { index, value ->
                    drawArc(
                        color = colors[index],
                        lastValue,
                        value,
                        useCenter = false,
                        style = Stroke(chartBarWidth.toPx(), cap = StrokeCap.Butt)
                    )
                    lastValue += value
                }
            }
        }
```

**Comment by developerchunk** [comment]
Thank you so much @oolyvi for raising and solving the issue, I appreciate your efforts to make the project and community better via every small effort. I have added the code it's just working fine, I am closing the issue. Please feel free to add new issues and contribute to the open-source. Thank you.

**Comment by oolyvi** [comment]
You are welcome, thanks to you for your supports. I added your sample to my code and it works perfectly fine. Thanks again!
